In [1]:
#importing numpy library
import numpy as np

In [8]:
#using 1D array using list/tuple
#use np.array()
a=np.array([1,2,3,4,5,6])
b=np.array((1,2,3,4,8,34))
print(type(a))
print(a)
print(type(b))
print(b)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]
<class 'numpy.ndarray'>
[ 1  2  3  4  8 34]


In [3]:
#2D creation using two lists
c=np.array([[1,2,3,4],[1,8,7,5]])
print(type(c))
print(c)

<class 'numpy.ndarray'>
[[1 2 3 4]
 [1 8 7 5]]


### Dimensions in numpy are called as axes
###### axis=0 represents rows(running vertically downwards)
###### axis=1 represents columns

In [9]:
#sum two list items
#in general we must use lamda fun or loops to do this
print(a)
print(b)
c=a+b
print(c)
print(type(c))

[1 2 3 4 5 6]
[ 1  2  3  4  8 34]
[ 2  4  6  8 13 40]
<class 'numpy.ndarray'>


In [10]:
#creating an arrays of fixed size

#from list
a=np.array([32,35,8,7658,54])
b=np.array([324,356,67,3,3467],dtype=float)
print(a,b)


#from tuple
c=np.array((91,54,64,32,67,43))
print(c)

[  32   35    8 7658   54] [3.240e+02 3.560e+02 6.700e+01 3.000e+00 3.467e+03]
[91 54 64 32 67 43]


In [11]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

## How to initialize np array when size is known

np.array()
np.zeroes()
np.ones()
np.random.random()
np.random.randint()
np.linspace()
np.full()
np.eye()
np.tile()

In [12]:
a=np.arange(10,25,6)
print("creating an array with elements within range",a)

creating an array with elements within range [10 16 22]


In [13]:
a=np.linspace(5,10,16)
print("creating an array with elem inserting n no of elem within range",a)


creating an array with elem inserting n no of elem within range [ 5.          5.33333333  5.66666667  6.          6.33333333  6.66666667
  7.          7.33333333  7.66666667  8.          8.33333333  8.66666667
  9.          9.33333333  9.66666667 10.        ]


In [14]:
a=np.full((2,2),6)
print("filling al the elements in array with a specific element",a)


filling al the elements in array with a specific element [[6 6]
 [6 6]]


In [15]:
a=np.random.random((2,3))
print("filling the elem in array with random numbers:",a)


filling the elem in array with random numbers: [[0.22997583 0.89406905 0.26949489]
 [0.30114991 0.35994116 0.47562163]]


In [20]:
np.zeros((5,5))   #sould give dimensions more than 1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
a=np.array([1,435,87,324,5])
print(a.size)

5


In [25]:
print(a.shape)

(5,)


In [29]:
a=np.array([[2,34,56,34],[234,54,6675,3]])
print(a.size)
print(a.shape)

8
(2, 4)


In [30]:
a = np.array((1,2,3))
print("array",a)

a=np.array([[0,1],[435,56],[1,2]])
print("no of elements in a",a.size)   #by default gives the no of elements
print("no of rowsmin a",np.size(a,0))  #no of rows
print("no of columns",np.size(a,1)) # no of columns



array [1 2 3]
no of elements in a 6
no of rowsmin a 3
no of columns 2


In [33]:
#creating identity matrix


a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
